name: Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          sudo apt update
          sudo apt install -y clang-format-20
          sudo ln -sf /usr/bin/clang-format-20 /usr/local/bin/clang-format
          which clang-format || echo "clang-format not found"
          clang-format --version

      - name: Check formatting
        run: make format-check
