name: Static Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup build environment
        run: |
          which clang++ || echo "clang++ not found"
          which clang-tidy || echo "clang-tidy not found"
          clang++ --version
          clang-tidy --version

      - name: Run static analysis
        run: make static-analysis
